language: python
install:
    - pip install coveralls
script:
    - python setup.py test --pytest-args "--cov-report xml --cov elastic_django tests/ --verbose --junit-xml=junit.xml --color=yes"
after_success:
    - coveralls
